#SPDX-License-Identifier: MIT-0
---
# tasks file for {{ slskd_service }}
- name: Create the workdir
  ansible.builtin.file:
    path: "{{ workdir }}/{{ slskd_service }}/config"
    state: directory
    mode: '0755'

- name: Create k8s namespace for {{ slskd_service }}
  kubernetes.core.k8s:
    name: "{{ slskd_kube_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install the helm-charts helm repo
  ansible.builtin.include_role:
    name: install-homelab-charts-repo

- name: Create config PV and PVC
  ansible.builtin.import_role:
    name: persistent-volume
  vars:
    pv_name_label: "{{ slskd_service }}-config"
    pv_kube_namespace: "{{ slskd_kube_namespace }}"
    pv_host_path: "{{ workdir }}/{{ slskd_service }}/config"
    pv_servicedir: "{{ workdir }}/{{ slskd_service }}"

- name: Create downloads PVC
  ansible.builtin.import_role:
    name: persistent-volume
  vars:
    pv_name_label: "{{ slskd_service }}-downloads"
    pv_kube_namespace: "{{ slskd_kube_namespace }}"
    pv_host_path: "{{ downloads_dir }}"
    pv_servicedir: "{{ workdir }}/{{ slskd_service }}"

- name: Deploy chart for {{ slskd_service }}
  kubernetes.core.helm:
    name: "{{ slskd_service }}"
    chart_ref: homelab-charts/{{ slskd_service }}
    release_namespace: "{{ slskd_kube_namespace }}"
    update_repo_cache: true
    wait: true
    timeout: "600s"
    values: "{{ lookup('ansible.builtin.template', 'templates/values.yml.j2') | from_yaml }}"

- name: Create Traefik ingressroutes
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'templates/traefik_ingress.yml.j2') | from_yaml }}"
