#SPDX-License-Identifier: MIT-0
---
# defaults file for mosquitto
msqt_kube_namespace: "mosquitto"
msqt_service: "mosquitto"
msqt_service_port: 1883
msqt_helm_repo: "https://bpmb82.github.io/homelab-charts/"
