#SPDX-License-Identifier: MIT-0
---
# defaults file for sabnzbd
snzb_kube_namespace: "sabnzbd"
snzb_service: "sabnzbd"
snzb_service_port: 8080
snzb_helm_repo: "https://bpmb82.github.io/homelab-charts/"
snzb_workdir: "/k3s"
