---
# tasks file for install-k3s
- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - curl
    - apparmor
    - apparmor-utils
    - git
    - jq
    - python3-kubernetes
    - python3-jsonpatch
    - python3-pyyaml
  when: ansible_facts["os_family"] == "Debian"

- name: Install for RedHat based OS
  when: ansible_facts["os_family"] == "RedHat"
  block:

    - name: Check if we are using dnf5
      ansible.builtin.shell: dnf --version | grep -c '^dnf5 version' || /bin/true
      register: ik3s_dnf5_present

    - name: Make sure we can use all the dnf modules on this system
      when: ik3s_dnf5_present.stdout == "1"
      block:

        - name: Check if we have python3-libdnf5 on the system
          ansible.builtin.shell: dnf list -q --installed | grep -c python3-libdnf5 || /bin/true
          register: ik3s_libdnf5_installed

        - name: Install python3-libdnf5 if not installed
          ansible.builtin.shell: dnf install -y python3-libdnf5
          when: ik3s_libdnf5_installed.stdout == "0"

    - name: Install prerequisites
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: 
        - curl
        - git
        - jq
        - python3-kubernetes
        - python3-jsonpatch
        - python3-pyyaml

    - name: Disable firewalld
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false
      ignore_errors: true

- name: Check if k3s is installed and the correct version
  ansible.builtin.shell: kubectl version -o json | jq '.serverVersion.gitVersion' || /bin/true
  register: ik3s_version

- name: Install helm
  ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

- name: Install Helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

- name: Install k3s when single_host
  when: ik3s_single_host and ik3s_version.stdout != ik3s_k3s_version
  block:

    - name: Save the private IP of this instance
      ansible.builtin.set_fact:
        ik3s_private_ip: "{{ ansible_facts['all_ipv4_addresses'] | select('match', '^' ~ node_ip_range) | first}}"

    - name: Find interface with private IP we just found
      ansible.builtin.set_fact:
        ik3s_selected_interface: "{{ item }}"
      loop: "{{ ansible_facts['interfaces'] }}"
      when: 
        - "vars['ansible_' + (item | replace('-', '_'))] is defined"
        - "'ipv4' in vars['ansible_' + (item | replace('-', '_'))]"
        - "vars['ansible_' + (item | replace('-', '_'))]['ipv4']['address'] == ik3s_private_ip"

    - name: Show selected interface
      ansible.builtin.debug:
        msg: "Interface selected for k3s is {{ ik3s_selected_interface }}"
      when: ik3s_debug

    - name: Install k3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ ik3s_k3s_version }} sh -s - --disable=traefik --write-kubeconfig-mode 600 --flannel-backend=none --disable-network-policy --disable servicelb

    - name: Install cilium cni
      ansible.builtin.include_tasks: install-cilium.yml

- name: Install k3s across nodes and init cluster
  when: ik3s_single_host == false
  block:

    - name: Init cluster on a single instance
      run_once: true
      block:

        - name: Save the private IP of this instance
          ansible.builtin.set_fact:
            ik3s_private_ip: "{{ ansible_all_ipv4_addresses | select('match', '^(10\\.|192\\.168\\.|198\\.)') | list | first }}"

        - name: Find interface with private IP we just found
          ansible.builtin.set_fact:
            ik3s_selected_interface: "{{ item }}"
          loop: "{{ ansible_interfaces }}"
          when: >
            ('ipv4' in ansible_facts[item]) and
            (ansible_facts[item]['ipv4']['address'] == ik3s_private_ip)

        - name: Show selected interface
          ansible.builtin.debug:
            msg: "Interface selected for flannel is {{ ik3s_selected_interface }}"
          when: ik3s_debug

        - name: Save the hostname so we can know which host we used for initialization
          ansible.builtin.shell: hostname
          register: ik3s_hostname_shell

        - name: Save the k3s join token
          ansible.builtin.set_fact:
            ik3s_k3s_token: "{{ lookup('community.general.random_string', length=32, special=false) }}"

        - name: Install k3s and initialize the cluster
          ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ ik3s_k3s_version }} K3S_TOKEN={{ ik3s_k3s_token }} sh -s - server --advertise-address={{ ik3s_private_ip }} --write-kubeconfig-mode 600 --cluster-init --tls-san={{ ik3s_private_ip }} --disable=traefik --node-ip={{ ik3s_private_ip }} --flannel-backend=none --disable-network-policy --disable servicelb
          when: ik3s_version.stdout != ik3s_k3s_version

        - name: Install cilium cni
          ansible.builtin.include_tasks: install-cilium.yml

    - name: Join the other instances to the cluster
      when: ik3s_hostname_shell.stdout != inventory_hostname
      block:

        - name: Save the private IP of this instance
          ansible.builtin.set_fact:
            ik3s_private_ip_secondaries: "{{ ansible_facts['all_ipv4_addresses'] | select('match', '^(10\\.|192\\.168\\.|198\\.)') | list | first }}"

        - name: Find interface with private IP we just found
          ansible.builtin.set_fact:
            ik3s_selected_interface_secondaries: "{{ item }}"
          loop: "{{ ansible_facts['interfaces'] }}"
          when: >
            ('ipv4' in ansible_facts[item]) and
            (ansible_facts[item]['ipv4']['address'] == ik3s_private_ip_secondaries)

        - name: Show selected interface
          ansible.builtin.debug:
            msg: "Interface selected for flannel is {{ ik3s_selected_interface_secondaries }}"
          when: ik3s_debug

        - name: Join other instances using the join token
          ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ ik3s_k3s_version }} K3S_TOKEN={{ ik3s_k3s_token }} sh -s - server --server https://{{ ik3s_private_ip }}:6443 --tls-san={{ ik3s_private_ip_secondaries }} --disable=traefik --node-ip={{ ik3s_private_ip_secondaries }} --flannel-backend=none --disable-network-policy
          when: ik3s_version.stdout != ik3s_k3s_version

    - name: Check cluster status
      when: ik3s_hostname_shell.stdout == inventory_hostname and ik3s_debug
      block:

        - name: Check the cluster from the first instance
          ansible.builtin.shell: kubectl get nodes
          register: ik3s_nodes

        - name: Show the output if debug is enabled
          ansible.builtin.debug:
            msg: "{{ ik3s_nodes.stdout }}"
          when: ik3s_debug

- name: Add KUBECONFIG and kubectl alias to bashrc and enable auto-completion
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      if command -v kubectl >/dev/null 2>&1
      then
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        source <(kubectl completion bash)
        alias k=kubectl
        complete -o default -F __start_kubectl k
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK KUBECTL"

# - name: Check if kubectl works
#   ansible.builtin.shell: kubectl version -o json | grep -c clientVersion || /bin/true # noqa: command-instead-of-module

# - name: Wait for the kube-system namespace to become available
#   ansible.builtin.shell: kubectl get pods --namespace kube-system --no-headers | wc -l # noqa: command-instead-of-module
#   register: ik3s_kube_system_pods
#   until: ik3s_kube_system_pods.rc == 0 and ik3s_kube_system_pods.stdout | int > 0
#   retries: 10
#   delay: 10
#   ignore_errors: true

# - name: Wait for all the pods to become available so we know kube-system is fully initialized
#   ansible.builtin.shell: kubectl wait --for=condition=Ready pod --all --namespace=kube-system --timeout=300s

- name: Install nfd if enabled
  ansible.builtin.include_tasks: install-nfd.yml
  when: ik3s_nfd_enabled
