#SPDX-License-Identifier: MIT-0
---
# tasks file for install-homelab-charts-repo
- name: Install or upgrade the helm-charts repo
  kubernetes.core.helm_repository:
    name: homelab-charts
    repo_url: "{{ ihc_repo_helm_repo }}"
    force_update: true
